# -*- coding: utf-8 -*-
"""data_processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbuF7BPerDp5-P7m-WnGc2PVSkcclhmb
"""

import matplotlib.pyplot as plt
import pandas as pd

def plot_spectra(wavelengths, measurements):
    """Plot the collected spectra."""
    plt.figure(figsize=(8, 5))
    for measurement_type, intensities in measurements.items():
        plt.plot(wavelengths, intensities, label=measurement_type)
    plt.xlabel("Wavelength (nm)")
    plt.ylabel("Intensity")
    plt.title("Spectra Measurements")
    plt.legend()
    plt.show()

def save_all_to_csv(wavelengths, measurements, filename="all_spectra_data.csv"):
    """Save all collected spectral data to a single CSV file."""
    data = []

    for measurement_type, intensities in measurements.items():
        for wl, intensity in zip(wavelengths, intensities):
            data.append([wl, intensity, measurement_type])

    df = pd.DataFrame(data, columns=["Wavelength", "Intensity", "Measurement Type"])
    df.to_csv(filename, index=False)
    print(f"All spectra data saved to {filename}")