
# -*- coding: utf-8 -*-
"""hotplate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175NiDS6_bgIkDaIlxQphXifoe6oEX1Ft
"""

import os
import sys
import threading
import serial
import time
import logging

# Add parent directory to sys.path if needed for external imports
pp = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))
sys.path.append(pp)

class Hotplate(threading.Thread):
    MAX_TEMPERATURE_C = 540

    def __init__(self, serial_port="/dev/ttyACM0", baud_rate=115200):
        super().__init__(name="Hotplate", daemon=True)
        self.serial = None
        self._current_temperature_c = 0
        self.target_temperature_c = 0
        self.logger = logging.getLogger("Main Logger")


        time.sleep(2)  # Allow time for Arduino to reset
        self.logger.info("Hotplate initialized and serial connection established.")
        
    def connect(self):
        """Connect to the control board and start the reader thread."""
        if self.is_connected():
            self.logger.error("Hotplate is already connected")
        
        
        try:
            self.serial = serial.Serial(self.com_port, 115200, timeout=None)
            self.logger.info(f"Connected to hotplate on port {self.com_port}")
        except serial.SerialException as e:
            self.logger.error(f"Error connecting to hotplate: {e}")
    
    def disconnect(self):
        if not self.is_connected():
            return
        
        self.serial.close()
        self.logger.debug("Hotplate Disconnected")
            
    def is_connected(self) -> bool:
        return self.serial is not None and self.serial.is_open

    def get_temperature(self):
        """Read actual temperature from Arduino via serial."""
        try:
            #self.serial.write(b"GET_TEMP\n")
            response = self.serial.readline().decode().strip()
            self.logger.debug(f"Raw response: {response}")

            if response.startswith("TEMP:"):
                self._current_temperature_c = float(response.split(":")[1])
            else:
                self.logger.warning(f"Invalid response from Arduino: {response}")
        except Exception as e:
            self.logger.error(f"Error reading temperature: {e}")

        return self._current_temperature_c
        
    def set_temperature(self, temperature):
        """Send set temperature to Arduino and verify response."""
        if temperature > self.MAX_TEMPERATURE_C:
            self.logger.warning(f"Temperature {temperature} exceeds max limit of {self.MAX_TEMPERATURE_C}°C")
            return

        self.target_temperature_c = temperature
        command = f"SET_TEMP {temperature}\n"
        try:
            self.serial.flushInput()  # Clears the input buffer
            time.sleep(0.1)  # Small delay to ensure clean communication

            self.serial.write(command.encode())
            self.serial.flush()  # Ensure data is sent immediately
            time.sleep(0.1)  # Small delay to allow Arduino to process
        
        # Read response from Arduino
            response = self.serial.readline().decode().strip()
            if response.startswith("TARGET SET"):
                self.logger.info(f"Confirmed target temperature: {response}")
            else:
                self.logger.warning(f"Unexpected response: {response}")    

        except Exception as e:    
            self.logger.error(f"Error sending temperature command: {e}")

    def run(self):
        """Continuously read temperature from Arduino."""
        self.logger.info("Hotplate thread started.")
        while True:
            temp = self.get_temperature()
            self.logger.info(f"Actual Temperature: {temp:.2f} °C")
            time.sleep(1)


if __name__ == "__main__":
    hotplate = Hotplate()
    hotplate.set_temperature(50)  # Example: Set target temperature to 50°C
    hotplate.start()  # Start background monitoring
